version: "3"

volumes:
  mongodata:

services:
  mongo:
    image: mongo:4.4
    restart: on-failure
    hostname: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: YMIT5VEUMWN49Ld
      MONGO_INITDB_DATABASE: defaultdb
    volumes:
      - mongodata:/data/db